version: '3'
services:
  node:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
